id: P003A3F59
initial_creation_type: input
source_metadata:
  title: Nyingma Mönlam Series
  language: nl
  description: 'The following texts are recited during the annual Nyingma Mönlam prayer
    festival in Bodhgaya:'
  volume:
    79483712b3704d3a966f125af8d6ca64:
      title: Verses of the Eight Noble Auspicious Ones
      parent: Eight Auspicious Ones
    a7de091d7c844f7393e93f99e9c2dc39:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Bodhisattva Vow
    7652e3f246c14e92954db7d86103a736:
      title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
      parent: Confession
    bf51e259ec2748e3a7724ef3ac22f35d:
      title: 'Accomplishing the Lama through the Seven-Line Prayer: A Special Teaching
        from the Lama Sangdü'
      parent: Seven-Line Prayer
    69ee16d3d28c45ca8c2b23d47f333fe0:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      parent: Zabtik Drolchok
    aa7db130046141f6a23192108035e28c:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Śākyamuni Practice
    3e6a3bc261d142ddb6a869f7c16da38c:
      title: A Brief Practice for Paying Homage and Making Offerings to the Buddha
        together with his retinue of Arhats
      parent: Sixteen Arhats
    ea92c92b9fd64988b52476cfc07a25fa:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Guru Rinpoche Visualization
    5fe16cf930fc40bbb1f63f8603022aaf:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Le'u Dünma
    039c0c40820c434a9891fd3bb0b47a9d:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Le'u Dünma
    2d2297fd7cee4703b2814d4c59d03102:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Le'u Dünma
    72550d2618bc4e7cb211844b0a0aa1f6:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Le'u Dünma
    3281529be41b4a5298965d6b9d005288:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Le'u Dünma
    987716694a2e442c83d51b173f6a518c:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Le'u Dünma
    732631de7b3c48c0b1bc7038f8953f2b:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Le'u Dünma
    7426b96b64704fb99806f17dfe1ec782:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Barché Lamsel
    f48b7d7a9b0240928a2f43b2a999ef23:
      title: The Prayer in Six Vajra Lines
      parent: Guru Rinpoche Prayers
    28003f6295694778a4c009d443a437a0:
      title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
      parent: Guru Rinpoche Prayers
    b84dbf97dd4e471d92ac37e4d2eaead1:
      title: 'Wisdom''s Bestowal: A Way to Accumulate the Recitation of the Tantra
        ''Chanting the Names of Mañjuśrī'' (Mañjuśrī Nāma Saṃgīti)'
      parent: Chanting the Names of Mañjuśrī
    bd3d6e0fdfc1483898c5129f075e08dc:
      title: Ārya Mañjuśrī Tantra Garbha
      parent: Mañjuśrī
    16f65f620f6f47b19beba779ff081a64:
      title: The Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
      parent: Mañjuśrī
    73f66b3d03854bb2ac4f18ffbaad1a03:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Heart Sūtra
    8b9738b0ace54d09a1167b6d5b015a49:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Blazing Wheel
    12deeeff32974d828e258a012021a573:
      title: 'The Blazing Tower: A Daily Practice of Uṣṇīṣa-Sitātapatrā'
      parent: Sitātapatrā
    8cdfe36beb6b45feba3985663ac5ecb6:
      title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
      parent: Siṃhamukhā
    a0a614519d214f8bad19912aad1bc71a:
      title: The Dhāraṇī of Amitāyus
      parent: Dhāraṇī of Amitāyus
    8e73e14a273d43ee96dfd465793ef4ff:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Zangchö Mönlam
    727079dd63d149f19da306a4baa47b48:
      title: Maitreya's Aspiration
      parent: Maitreya's Aspiration
    65193311c0004ed09a58860e87c91317:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Aspiration to Generate Bodhicitta
    a5d617d7b2204c84b83656845f37ef89:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Kunzang Mönlam
    96b0887a3a854f29b3cebf5528b1e097:
      title: Brief Sukhāvatī Aspiration
      parent: Amitābha Mönlam
    d20c2be8c28b43b78aba0f24e14d16d4:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      parent: Amitābha Mönlam
    41a5fb9a20e842c7bca62886b736cd52:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration of Vajradhātu Maṇḍala
    671a7cf990d846f3911a0c97db8441ce:
      title: Yeshe Tsogyal's Prayer
      parent: Yeshe Tsogyal’s Prayer
    0abffc746ed643da982d824837e653e4:
      title: Prayer for Dispelling Famine
      parent: Thangtong Gyalpo Prayers
    c29dd6247d7c4d058a2a50334c283864:
      title: 'The Verses that Saved Sakya from Sickness: A Prayer for Pacifying the
        Fear of Disease'
      parent: Thangtong Gyalpo Prayers
    3ab596c2f88e42ac84a9aa30af5a882b:
      title: 'The Sage''s Powerful Words of Truth: A Prayer for the Spread of the
        Omniscient Buddha''s Teachings'
      parent: Sage's Powerful Words of Truth
    3f1d503fff0b444ca547090eb7c66228:
      title: 'The Rishi''s Maledictory Incantation: An Invocation of Wisdom Mind and
        Sacred Pledges for Reversing the Disturbances and Agitations of Dark Times
        In the Form of an Aspiration Prayer'
      parent: Rishi's Maledictory Incantation
    cc6c7190ff59440eae947da112c78d47:
      title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara,
        the Glorious Victor, to Avert the Final War'
      parent: Adamantine Magical Wheel
    a0f7b0622fd5486aaa91cea235d9e1ec:
      title: 'The Resounding Drum of Truth: A Prayer and Aspiration'
      parent: Resounding Drum of Truth
    5182516503c04203beea3e23bd86383e:
      title: The Prayer of the Words of Truth
      parent: Words of Truth
    f12b48c711274bee803fe186322c4fb6:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Ground, Path & Fruition Prayer
    c480659d77fc448a8a5865e231e7a66c:
      title: The Secret Vajra Knot
      parent: Secret Vajra Knot
    05e3ae3c6fd34bd3b7ed1448fabbf66e:
      title: Prayer for the Long Life of His Holiness the Dalai Lama
      parent: Long Life Prayers
    2d6a211723fb447193ffa302c0a9cf96:
      title: 'The Music of Immortality: A Prayer for the Long Life of His Holiness
        the Dalai Lama'
      parent: Long Life Prayers
    5e471bd9380744e2af0d20c7485e8613:
      title: General Long-Life Prayer
      parent: Long Life Prayers
    fb45e7f020844150beb314e57ef66deb:
      title: 'The Melodious Song of Immortality: A Prayer for Long Life'
      parent: Long Life Prayers
    4ae9864e5fc247408f0b9bc19a6ffb31:
      title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration
        for the Flourishing and Spread of the Ancient Translation Tradition'
      parent: Prayer for Spread of Nyingma Tradition
    613c87f47f2c452c882ccb6c7aee9ffd:
      title: 'Final Words: The Essential Advice'
      parent: Final Words
created_at: '2022-03-01T04:58:16.998631'
last_modified_at: '2022-03-01T04:58:16.998634'
